# for local development
version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  quasar:
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/frontend'
    command: /bin/sh -c "yarn && quasar dev"

volumes:
  todo-python-quasar: